const HTML = "<!DOCTYPE html>\n<html lang=\"id\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<title>LihatYuk</title>\n<style>\n*{box-sizing:border-box}body{margin:0;background:#0b0b0f;color:#fff;font-family:Arial,sans-serif}\nheader{height:64px;padding:0 6%;display:flex;align-items:center;background:#111116;position:sticky;top:0}\n.logo{font-size:25px;font-weight:800;color:#ff1744}\nnav{margin-left:35px;display:flex;gap:25px;color:#bbb}\nnav a{color:inherit;text-decoration:none}\nmain{padding:60px 6%}\n.hero{min-height:420px;display:flex;align-items:center}\nh1{font-size:clamp(42px,7vw,72px);margin:0 0 20px}\np{color:#aaa;font-size:17px;line-height:1.6;max-width:600px}\nbutton{border:0;border-radius:7px;padding:14px 24px;background:#ff1744;color:#fff;font-weight:bold;font-size:15px}\nsection{margin-top:40px}.title{font-size:22px;margin-bottom:18px}\n.cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:15px}\n.card{background:#17171d;border-radius:8px;overflow:hidden}\n.poster{height:230px;background:#25252d}\n.info{padding:12px}.info b{display:block}.info small{color:#777}\nfooter{margin-top:80px;padding:30px;text-align:center;color:#666;border-top:1px solid #222}\n</style>\n</head>\n<body>\n<header>\n<div class=\"logo\">LihatYuk</div>\n<nav>\n<a href=\"#\">Home</a>\n<a href=\"#film\">Film</a>\n<a href=\"#series\">Series</a>\n<a href=\"#live\">Live</a>\n</nav>\n</header>\n\n<main>\n<div class=\"hero\">\n<div>\n<h1>Semua tontonan<br>di satu tempat.</h1>\n<p>Selamat datang di LihatYuk. Temukan film, series, video, dan live streaming favoritmu.</p>\n<button onclick=\"alert('Player LihatYuk')\">▶ Mulai Nonton</button>\n</div>\n</div>\n\n<section id=\"film\">\n<div class=\"title\">🔥 Sedang Populer</div>\n<div class=\"cards\">\n<div class=\"card\"><div class=\"poster\"></div><div class=\"info\"><b>Konten Pilihan</b><small>Film • 2026</small></div></div>\n<div class=\"card\"><div class=\"poster\"></div><div class=\"info\"><b>Movie Terbaru</b><small>Film • 2026</small></div></div>\n<div class=\"card\"><div class=\"poster\"></div><div class=\"info\"><b>LihatYuk Picks</b><small>Series • 2026</small></div></div>\n</div>\n</section>\n\n<section id=\"series\">\n<div class=\"title\">🎬 Series Terbaru</div>\n<div class=\"cards\">\n<div class=\"card\"><div class=\"poster\"></div><div class=\"info\"><b>Series 01</b><small>Series • 2026</small></div></div>\n<div class=\"card\"><div class=\"poster\"></div><div class=\"info\"><b>Series 02</b><small>Series • 2026</small></div></div>\n</div>\n</section>\n\n<section id=\"live\">\n<div class=\"title\">🔴 Live Streaming</div>\n<p>Belum ada siaran live.</p>\n</section>\n</main>\n\n<footer>© 2026 LihatYuk</footer>\n</body>\n</html>\n"

export default {
  async fetch(request, env) {
    return new Response(HTML, {
      headers: {
        "content-type": "text/html; charset=UTF-8"
      }
    });
  }
};
